// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlD20uBYMhIpGC8tVVjhsnw4eIEjOAoCo',
    appId: '1:826678515935:web:66258066ff5c05e23e716a',
    messagingSenderId: '826678515935',
    projectId: 'educat-5da67',
    authDomain: 'educat-5da67.firebaseapp.com',
    storageBucket: 'educat-5da67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR-Pah8AHPpRD2NHl4-WunKbb01jEfAv8',
    appId: '1:826678515935:android:aac79a324e325d0c3e716a',
    messagingSenderId: '826678515935',
    projectId: 'educat-5da67',
    storageBucket: 'educat-5da67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAvmbRKh3I3kidtgcbLWPSTIdShD0F45A',
    appId: '1:826678515935:ios:700ce6bc4c28a1663e716a',
    messagingSenderId: '826678515935',
    projectId: 'educat-5da67',
    storageBucket: 'educat-5da67.appspot.com',
    iosClientId: '826678515935-2uijt5oohqho6g56p1lt3nip6vkommj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.educat',
  );
}
